### ISSUE TITLE
Lanzaras una versión para pre-procesadores (Stylus, Less, Sass,...) para este framework?

### ISSUE THREAD

**Issue by JonDotsoy** [escueladigital/ED-GRID#1]

**Comment by escueladigital** [comment]
Con Sass (es el que yo uso). Apenas me dé el tiempo.

**Comment by alfa30** [comment]
He Preparado el código en [Stylus](http://learnboost.github.io/stylus/).
[github.com/alfa30/ed-grid](https://github.com/alfa30/ed-grid)

**Comment by escueladigital** [comment]
Genial!

**Comment by francocorreasosa** [comment]
Version en SASS https://github.com/AtomLife/AtomUI/blob/master/src/sass/grid.scss

**Comment by escueladigital** [comment]
Hay que meterle variables, funciones y mixins para sass. También trabajo en eso.

**Comment by alfa30** [comment]
Tengo implemtado nuevos cambios dentro del framework. 

(alfa30/ed-grid)[https://github.com/alfa30/ed-grid] :point_left:

¿Ya tienes fecha de lanzamiento para la primera version?

**Comment by escueladigital** [comment]
Aun no, estoy trabajando en el componentes mara menus responsive y la versión Sass con la estructura de proyecto.

**Comment by alfa30** [comment]
Estaré atento a cambios del framework para generar la estructura en stylus.

**Comment by escueladigital** [comment]
Ya lo tengo casi listo en Sass. Portarlo a stylus seria acomodar la sintaxis, pero como no domino su sintaxis, sería genial una manito.

**Comment by jonDotsoy** [comment]
​Te puede ayudar con eso, estoy siguiendo los cambios del framework. Puede
visitar el repositorio en [jonDotsoy/ed-grid](
https://github.com/jonDotsoy/ed-grid)​.

**Comment by edwingromero** [comment]
Aqui les dejo una versión en stylus de ed-grid https://github.com/edwingromero/ed-grid-stylus
