### ISSUE TITLE
Módulo de NPM

### ISSUE THREAD

**Issue by Revod** [escueladigital/ED-GRID#17]
El Módulo de NPM de ed-grid ya funciona correctamente?

**Comment by carloscuatin** [comment]
@Revo la verdad es que no encontré al chico que gestiona el package en npm y la verdad estoy que mejor creó uno nuevo, Si alguien lo conoce por favor contactarme con el

**Comment by escueladigital** [comment]
me parece que es franco correa, aunque no estoy seguro, ya le pregunto.

**Comment by francocorreasosa** [comment]
Hola, soy yo si. Lo que hice fue que cuando salio la primera version de ed-grid (super mega alpha) reservé el nombre en Bower y NPM. Al ED-GRID ser un modulo de frontend sin JavaScript (solo CSS/SASS) no tiene sentido crear un modulo en NPM, sino mas bien en Bower. Solo lo hice para reservar el nombre por si en el futuro tiene componentes de JS. Espero haber aclarado la duda.

**Comment by carloscuatin** [comment]
claro entiendo, pero ejemplo si tu no usas bower  debido que a mi criterio ps es una dependencia más ya que debes tener node para poderlo correr. Es ambiguo ya que si tienes node y npm es suficiente para gestionar tus paquetes ejemplo normalizecss se puede instalar desde npm, por eso la importancia

**Comment by escueladigital** [comment]
pero el npm no se trae el proyecto desde github? que habria que cambiarle?

**Comment by carloscuatin** [comment]
el package.json creo que esta jalando el style incorrecto, por eso no logra traerse el paquete

**Comment by Revod** [comment]
Claro y yo soy de los que esta migrando de usar bower y esta empezando a usar los modulos de npm @francocorreasosa, y creo que @carloscuatin igual asi como muchas personas porque como dice Carlos para mi criterio tambien termina siendo una dependencia mas

**Comment by carloscuatin** [comment]
@escueladigital lo que pasa es que cuando haces npm install --save ed-grid el trata de traerse esto https://registry.npmjs.org/ed-grid/-/ed-grid-2.0.0.tgz que ya esta empaquetado en npm, entonces se tiene que actualizar

**Comment by francocorreasosa** [comment]
@carloscuatin Lo que podemos hacer es lo siguiente, te doy permisos en el paquete y lo manejas vos. Asi se que estará actualizado.

**Comment by carloscuatin** [comment]
@francocorreasosa me parece perfecto :+1:

**Comment by carloscuatin** [comment]
@Revod listo el package en npm anda funcionando aqui te dejo el links
https://www.npmjs.com/package/ed-grid para que revises, yo ya lo probe y quedo bien registrado

**Comment by Revod** [comment]
@carloscuatin excelente Carlos, ahora a sacarle provecho a ED-Grid como se debe (:
