### ISSUE TITLE
Use postcss ?

### ISSUE THREAD

**Issue by carloscuatin** [escueladigital/ED-GRID#24]

**Comment by escueladigital** [comment]
Sass + Postcss.

**Comment by carloscuatin** [comment]
genial 🎉

**Comment by Revod** [comment]
@carloscuatin  Alguna noticia sobre ED Grid? solo vi algun video por alli que hablaron sobre ED UI pero existe alguna manera en ayudar y aportar en el desarollo?

**Comment by carloscuatin** [comment]
@Revod no estoy muy enterado de lo nuevo de ED GRID la verdad el que te sacara de la duda es @escueladigital 👻
