### ISSUE TITLE
Ver framework ligeros

### ISSUE THREAD

**Issue by giancarlocp** [escueladigital/ED-GRID#3]
Buscando framework CSS ligeros encontré y recomiendo mirar **Pure**(jquery) y **Picnic**.

Resumen tras googlear:

http://www.hongkiat.com/blog/bootstrap-alternatives/
skeleton
cardinalcss
concisecss
powertocss
furtive
basscss
mueller
tuktuk
base
toast

http://stackoverflow.com/questions/9212536/alternatives-to-twitter-bootstrap
**Blueprint.css**

**Zurb Foundation** - comprehensive alternative, includes lots of templates
**Skeleton** - minimal option
**Initialzr** - includes a basic responsive template by default, but can also integrate with Bootstrap (mainly for integrating HTML5 Boilerplate with Bootstrap)
**Flat UI Kit** - based on Bootstrap, but lots of styles and colours in the 'flat' design.
**Gumby** - Responsive grid, uses Sass by default
**Inuit** - Based on Sass and uses OOCSS

http://www.monolinea.com/css-frameworks-comparison/
  ⋅⋅⋅ **middleweights**
Gumby
Groundwork
 ⋅⋅⋅ **lightweights**
Pure
Base
KubeCSS

**Comment by escueladigital** [comment]
He visto Pure CSS y Skeleton. MI enfoque es más hacia Skeleton, una base super ligera sobre la cual construir.
