### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by carloslfu** [escueladigital/ed-grid#4]
Hola Alvaro, ed-grid esta genial y me gustaria saber bajo que licencia lo puedo usar. Podrias añadir un archivo o una anotacion en el repositorio acerca de la licencia?. Gracias por tu tiempo.

**Comment by escueladigital** [comment]
Hola, no me he tomado el trabajo de definir la licencia exacta. Pero en toda la documentacion dice claramente que puedes usarlo libremente (sin costo) en tus proyectos e incluso crear tus propias versiones derivadas (open source).

Gracias por el interes en ED grid.

Álvaro Felipe Chávez
Director de Proyectos
www.alvarofelipe.net
Cel: 943-851-562 (RPM)
      

Asoc. Buenos Aires, Mz H - Lote 14, 1er piso, SJL - Lima 036 | Tel: 388-0975
www.escueladigital.pe   /escueladigital.pe      /edigitalperu





---- On Sun, 17 May 2015 14:25:56 -0500 Carlos Galarza &lt;notifications@github.com&gt; wrote ---- 

Hola Alvaro, ed-grid esta genial y me gustaria saber bajo que licencia lo puedo usar. Podrias añadir un archivo o una anotacion en el repositorio acerca de la licencia?. Gracias por tu tiempo.

**Comment by carloslfu** [comment]
Gracias por la rapida respuesta, un saludo.
